name: Sync selected files from private mika-ai

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Every day at 3:00 UTC

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: "Debug: Show initial info"
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -alh

      - name: Clone private repo (mika-ai)
        env:
          PAT: ${{ secrets.MIKA_AI_PAT }}
        run: |
          set -x
          git clone https://osmarbetancourt:"${PAT}"@github.com/osmarbetancourt/mika-ai.git private_mika_ai
          echo "Private repo contents:"
          ls -alh private_mika_ai

      - name: Copy desired files and folders
        run: |
          set -x
          rm -rf Assets/Scripts
          rm -f python_scripts/mika_func.md
          mkdir -p Assets
          cp -r private_mika_ai/Assets/Scripts Assets/
          mkdir -p python_scripts
          cp private_mika_ai/python_scripts/mika_func.md python_scripts/
          echo "After copying files:"
          ls -alh Assets/Scripts || true
          ls -alh python_scripts || true

      - name: "Debug: Git status before commit"
        run: |
          git status
          git config --list
          git remote -v

      - name: Commit and push if changed
        env:
          PAT: ${{ secrets.MIKA_AI_PAT }}
        run: |
          set -x
          git config user.name "osmarbetancourt"
          git config user.email "oaba.dev@gmail.com"
          git add Assets/Scripts python_scripts/mika_func.md
          git status
          git diff --cached
          git diff --cached --quiet || git commit -m "Sync Assets/Scripts and mika_func.md from private repo"
          git log -1
          echo "About to push..."
          git push https://osmarbetancourt:${PAT}@github.com/osmarbetancourt/project-mika-ai.git HEAD:main || { echo 'Push failed!'; exit 1; }
